# Setup MySQL and MariaDB
#

- name: Ensure MariaDB is running/enabled
  service:
    name: mariadb
    state: started
    enabled: yes
  tags:
    - database
  notify:
    - Restart apache

- name: Create MySQL Database
  mysql_db: 
    name: "{{ wp_mysql_db }}" 
    state: present
  tags:
    - database
  notify:
    - Restart apache

- name: Create MySQL user
  mysql_user:
    login_user: "root"
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}" 
    priv: '*.*:ALL' 
  tags:
    - database
  notify:
    - Restart apache


