# Setup MySQL and MariaDB
#

- name: Create MySQL Database
  mysql_db: 
    name: "{{ wp_mysql_db }}" 
    state: present
  notify:
    - Restart apache

- name: Create MySQL user
  mysql_user:
    login_user: "root"
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}" 
    priv: '*.*:ALL,GRANT' 
  notify:
    - Restart apache

- name: Ensure all services are running
  service:
    name: "{{ items }}"
    with_items:
      - httpd
      - mariadb
    state: started
    enabled: yes
 

