- hosts: moscow-server
  remote_user: "{{ ssh_user }}" 
  vars_files:
    - group_vars/vars.yml

  roles:
      - wp-dependencies
      - geerlingguy.pip
      - robertdebock.httpd
      - wp-install
      

