---
# tasks file for wp-dependencies
#
- name: Update system
  yum: 
    name: "*" 
    state: latest
  tags:
    - system


# PHP-7.0
- name: Install php-7.0
  include_tasks: php-7.yml
  tags:
    - php

- name: Install dependencies
  yum: 
    name: "{{ dependencies_pkg }}" 
    state: present
    update_cache: yes
  tags:
    - system

- name: Setup database and run
  include_tasks: database.yml
  tags:
    - database

      #  import_role:
      #- name: Install httpd from ansible galaxy
      #  import_role: 
      #    name: robertdebock.httpd
      #  tags:
      #    - galaxy
      #    - httpd
      #

