---
# tasks file for wp-dependencies
#
- name: Update system
  yum: 
    name: "*" 
    state: latest
  tags:
    - system

- name: Install epel repo, yum-utils
  yum:
    name: ['https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm', 'yum-utils']
    state: present
  tags:
    - system

- name: Install dependencies
  yum: 
    name: "{{ dependencies_pkg }}" 
    state: present
    update_cache: yes
  tags:
    - system

- name: Install httpd from galaxy ansible
  import_role: 
    name: robertdebock.httpd

# PHP-7.0
- name: Install php-7.0
  include_tasks: php-7.yml
  tags:
    - php

